Pandas is a powerful, open-source data analysis and manipulation tool built on top of the Python programming language. It offers data structures and operations for manipulating numerical tables and time series, making data analysis more accessible and efficient

In [1]:
# Install the pandas library. Most probably this is installed on you too because of Anaconda
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# Importing pandas
import pandas as pd

In [3]:
# Creating a DataFrame
df = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Age': [25, 36, 17, 8, 3, 12, 18, 24],
    'Gender': ['male', 'female', 'not stated', 'male','male','female','not stated','female']
})

In [4]:
df

   ID  Age      Gender
0   1   25        male
1   2   36      female
2   3   17  not stated
3   4    8        male
4   5    3        male
5   6   12      female
6   7   18  not stated
7   8   24      female

In [7]:
# Common functions
df.head(6)

   ID  Age      Gender
0   1   25        male
1   2   36      female
2   3   17  not stated
3   4    8        male
4   5    3        male
5   6   12      female

In [10]:
df.tail(1)

   ID  Age  Gender
7   8   24  female

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Age     8 non-null      int64
 2   Gender  8 non-null      object
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes

In [12]:
df.describe()

            ID        Age
count  8.00000   8.000000
mean   4.50000  17.875000
std    2.44949  10.494046
min    1.00000   3.000000
25%    2.75000  11.000000
50%    4.50000  17.500000
75%    6.25000  24.250000
max    8.00000  36.000000

In [13]:
df

   ID  Age      Gender
0   1   25        male
1   2   36      female
2   3   17  not stated
3   4    8        male
4   5    3        male
5   6   12      female
6   7   18  not stated
7   8   24      female

In [16]:
df['Gender']

0          male
1        female
2    not stated
3          male
4          male
5        female
6    not stated
7        female
Name: Gender, dtype: object

In [19]:
df[['Gender']]

       Gender
0        male
1      female
2  not stated
3        male
4        male
5      female
6  not stated
7      female

In [22]:
df['Gender'].value_counts()

Gender
male          3
female        3
not stated    2
Name: count, dtype: int64

In [23]:
df

   ID  Age      Gender
0   1   25        male
1   2   36      female
2   3   17  not stated
3   4    8        male
4   5    3        male
5   6   12      female
6   7   18  not stated
7   8   24      female

In [27]:
# slicing
df.loc[0,'Age']

25

In [26]:
df.iloc[0,1]

25

In [28]:
df.loc[5,'Gender']

'female'

In [29]:
df2 = pd.DataFrame({'ID': [1, 2, 8, 17], 'Monthly Income in Thousand $': [3, 9, 4.5, 3.4]})

In [30]:
df2

   ID  Monthly Income in Thousand $
0   1                           3.0
1   2                           9.0
2   8                           4.5
3  17                           3.4

In [31]:
df

   ID  Age      Gender
0   1   25        male
1   2   36      female
2   3   17  not stated
3   4    8        male
4   5    3        male
5   6   12      female
6   7   18  not stated
7   8   24      female

In [36]:
# merge
merged = pd.merge(df, df2, on='ID', how='left')
merged

   ID  Age      Gender  Monthly Income in Thousand $
0   1   25        male                           3.0
1   2   36      female                           9.0
2   3   17  not stated                           NaN
3   4    8        male                           NaN
4   5    3        male                           NaN
5   6   12      female                           NaN
6   7   18  not stated                           NaN
7   8   24      female                           4.5

In [37]:
# null checker
merged.isna()

      ID    Age  Gender  Monthly Income in Thousand $
0  False  False   False                         False
1  False  False   False                         False
2  False  False   False                          True
3  False  False   False                          True
4  False  False   False                          True
5  False  False   False                          True
6  False  False   False                          True
7  False  False   False                         False

In [38]:
# null counts for columns
merged.isna().sum()

ID                              0
Age                             0
Gender                          0
Monthly Income in Thousand $    5
dtype: int64

In [39]:
# type
type(merged.loc[0,'Gender'])

str

In [40]:
merged.loc[0,'Gender']

'male'

In [43]:
type(merged[['Gender']])

pandas.core.frame.DataFrame

In [44]:
merged[['Gender']]

       Gender
0        male
1      female
2  not stated
3        male
4        male
5      female
6  not stated
7      female

In [45]:
# value_counts
merged['Gender'].value_counts()

Gender
male          3
female        3
not stated    2
Name: count, dtype: int64

In [46]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            8 non-null      int64
 1   Age                           8 non-null      int64
 2   Gender                        8 non-null      object
 3   Monthly Income in Thousand $  3 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 388.0+ bytes

In [52]:
# select_dtypes
numerics = merged.select_dtypes(include=['object'])
numerics

       Gender
0        male
1      female
2  not stated
3        male
4        male
5      female
6  not stated
7      female

In [56]:
# filtering
merged[merged['Gender'] == 'not stated']

   ID  Age      Gender  Monthly Income in Thousand $
2   3   17  not stated                           NaN
6   7   18  not stated                           NaN

In [57]:
# groupby
grouped = merged.groupby('Gender')['Age'].mean()
grouped

Gender
female        24.0
male          12.0
not stated    17.5
Name: Age, dtype: float64

In [58]:
merged

   ID  Age      Gender  Monthly Income in Thousand $
0   1   25        male                           3.0
1   2   36      female                           9.0
2   3   17  not stated                           NaN
3   4    8        male                           NaN
4   5    3        male                           NaN
5   6   12      female                           NaN
6   7   18  not stated                           NaN
7   8   24      female                           4.5

In [60]:
# sort_values
sorted_df = merged.sort_values(by='Age', ascending=True)
sorted_df

   ID  Age      Gender  Monthly Income in Thousand $
4   5    3        male                           NaN
3   4    8        male                           NaN
5   6   12      female                           NaN
2   3   17  not stated                           NaN
6   7   18  not stated                           NaN
7   8   24      female                           4.5
0   1   25        male                           3.0
1   2   36      female                           9.0